// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trivozhno.Infrastructure.Persistence;

#nullable disable

namespace Trivozhno.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BotDb))]
    partial class BotDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trivozhno.Infrastructure.Groq.ApiUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CachedTokens")
                        .HasColumnType("integer");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<int>("ReasoningTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("Summary")
                        .HasColumnType("boolean");

                    b.Property<int>("Tokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("Model", "At");

                    b.ToTable("ApiUsage");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.BotUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AiNoticeShown")
                        .HasColumnType("boolean");

                    b.Property<bool>("Blocked")
                        .HasColumnType("boolean");

                    b.Property<string>("ChatStyleProfile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CustomTime")
                        .HasColumnType("boolean");

                    b.Property<long?>("HistoryCursorId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("HistoryCursorTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HistoryEndLocal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("HistoryLastId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("HistoryLastTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemoryVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("MoodConsentShown")
                        .HasColumnType("boolean");

                    b.Property<bool>("MoodContextEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PendingAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PendingFrequency")
                        .HasColumnType("integer");

                    b.Property<bool>("ReminderPromptShown")
                        .HasColumnType("boolean");

                    b.Property<string>("ReturnState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SummaryNextAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("UiToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MemoryVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("MoodDerived")
                        .HasColumnType("boolean");

                    b.Property<bool>("QueueNoticeShown")
                        .HasColumnType("boolean");

                    b.Property<long?>("ReplyToId")
                        .HasColumnType("bigint");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourcesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UpdateId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReplyToId")
                        .IsUnique();

                    b.HasIndex("UpdateId")
                        .IsUnique();

                    b.HasIndex("Status", "Id");

                    b.HasIndex("UserId", "Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasAnswer")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ConfessionSubmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DraftId")
                        .IsUnique();

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ConversationSummary", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("CoveredThroughId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Summaries");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MoodValue")
                        .HasColumnType("integer");

                    b.Property<bool>("ReplaceOnNext")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Drafts");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.DraftPart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "Id");

                    b.ToTable("DraftParts");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.InboxUpdate", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Status", "AvailableAt", "Id");

                    b.ToTable("Inbox");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.KnowledgeChunk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Heading")
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<int>("PageEnd")
                        .HasColumnType("integer");

                    b.Property<int>("PageStart")
                        .HasColumnType("integer");

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<string[]>("Terms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Terms");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Terms"), "gin");

                    b.HasIndex("SourceId", "Ordinal")
                        .IsUnique();

                    b.ToTable("Chunks");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.KnowledgeSource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImportVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.MoodEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RecordedAt", "Id");

                    b.ToTable("Moods", t =>
                        {
                            t.HasCheckConstraint("CK_Mood_Value", "\"Value\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("Destination")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Markup")
                        .HasColumnType("text");

                    b.Property<long?>("MemoryVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<int>("PartIndex")
                        .HasColumnType("integer");

                    b.Property<long?>("ReminderVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TelegramMessageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Destination", "Id");

                    b.HasIndex("OperationId", "PartIndex")
                        .IsUnique();

                    b.HasIndex("Status", "AvailableAt", "Id");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.PollCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("Offset")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ReminderOccurrence", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ScheduledAt")
                        .IsUnique();

                    b.ToTable("Occurrences");
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ReminderSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<string>("LocalTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("NextDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.HasIndex("Enabled", "NextDueAt");

                    b.ToTable("Reminders", t =>
                        {
                            t.HasCheckConstraint("CK_Reminder_Interval", "\"IntervalDays\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ChatMessage", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.BotUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ChatSession", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.BotUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ConfessionSubmission", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.BotUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ConversationSummary", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.BotUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.Draft", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.BotUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.DraftPart", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.Draft", null)
                        .WithMany()
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.KnowledgeChunk", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.KnowledgeSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.MoodEntry", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.BotUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.BotUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ReminderOccurrence", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.BotUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trivozhno.Infrastructure.Persistence.ReminderSetting", b =>
                {
                    b.HasOne("Trivozhno.Infrastructure.Persistence.BotUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
